apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "chart.fullname" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "chart.fullname" . }}-serving-cert
  labels:
  {{- include "chart.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "chart.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-v1-sidecar
  failurePolicy: Fail
  name: morascache.kb.io
  rules:
  - apiGroups:
    - ""
    - core
    - batch
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    - jobs
  sideEffects: None