---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1-sidecar
  failurePolicy: Fail
  name: morascache.kb.io
  rules:
  - apiGroups:
    - ""
    - "core"
    - "batch"
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    - jobs
  sideEffects: None
