# permissions for end users to edit orascaches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: orascache-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: oras-operator
    app.kubernetes.io/part-of: oras-operator
    app.kubernetes.io/managed-by: kustomize
  name: orascache-editor-role
rules:
- apiGroups:
  - cache.converged-computing.github.io
  resources:
  - orascaches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.converged-computing.github.io
  resources:
  - orascaches/status
  verbs:
  - get
